changelog:
  exclude:
    labels:
      - dependencies
      - contributors
    authors:
      - app/dependabot
  categories:
    - title: Deprecation notices
      labels:
        - deprecation
    - title: New filter templates
      labels:
        - new-filter
    - title: Updated filter templates
      labels:
        - filter-data
    - title: Self hosting
      labels:
        - self-hosting
    - title: New features
      labels:
        - "*"
