linters:
  enable:
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - exhaustive
    - gochecknoinits
    - gocritic
    - goimports
    - makezero
    - misspell
    - nilnil
    - prealloc
    - predeclared
    - unconvert

linters-settings:
  depguard:
    list-type: denylist
    packages-with-error-message:
      - gopkg.in/yaml.v2: 'use gopkg.in/yaml.v3 instead'
