ALTER TABLE filter_lists ALTER COLUMN user_id SET DATA TYPE TEXT;
ALTER TABLE filter_instances ALTER COLUMN user_id SET DATA TYPE TEXT;
ALTER TABLE banned_users ALTER COLUMN user_id SET DATA TYPE TEXT;
ALTER TABLE user_preferences ALTER COLUMN user_id SET DATA TYPE TEXT;