// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type FilterInstance struct {
	ID           int32
	UserID       uuid.UUID
	FilterListID int32
	FilterName   string
	Params       pgtype.JSONB
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}

type FilterList struct {
	ID        int32
	UserID    uuid.UUID
	Token     uuid.UUID
	CreatedAt time.Time
}
