// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: qLists.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countListsForUser = `-- name: CountListsForUser :one
SELECT COUNT(*)
FROM filter_lists
WHERE user_id = $1
`

func (q *Queries) CountListsForUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countListsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListForUser = `-- name: CreateListForUser :one
INSERT INTO filter_lists (user_id)
VALUES ($1)
RETURNING token
`

func (q *Queries) CreateListForUser(ctx context.Context, userID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createListForUser, userID)
	var token uuid.UUID
	err := row.Scan(&token)
	return token, err
}

const getListForToken = `-- name: GetListForToken :one
SELECT id, user_id, downloaded
FROM filter_lists
WHERE token = $1
LIMIT 1
`

type GetListForTokenRow struct {
	ID         int32
	UserID     string
	Downloaded bool
}

func (q *Queries) GetListForToken(ctx context.Context, token uuid.UUID) (GetListForTokenRow, error) {
	row := q.db.QueryRow(ctx, getListForToken, token)
	var i GetListForTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.Downloaded)
	return i, err
}

const getListForUser = `-- name: GetListForUser :one
SELECT token,
       downloaded,
       (SELECT COUNT(*) FROM filter_instances WHERE filter_instances.user_id = $1) AS instance_count
FROM filter_lists
WHERE filter_lists.user_id = $1
LIMIT 1
`

type GetListForUserRow struct {
	Token         uuid.UUID
	Downloaded    bool
	InstanceCount int64
}

func (q *Queries) GetListForUser(ctx context.Context, userID string) (GetListForUserRow, error) {
	row := q.db.QueryRow(ctx, getListForUser, userID)
	var i GetListForUserRow
	err := row.Scan(&i.Token, &i.Downloaded, &i.InstanceCount)
	return i, err
}

const hasUserDownloadedList = `-- name: HasUserDownloadedList :one
SELECT downloaded
FROM filter_lists
WHERE filter_lists.user_id = $1
LIMIT 1
`

func (q *Queries) HasUserDownloadedList(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserDownloadedList, userID)
	var downloaded bool
	err := row.Scan(&downloaded)
	return downloaded, err
}

const markListDownloaded = `-- name: MarkListDownloaded :exec
UPDATE filter_lists
SET downloaded    = true,
    downloaded_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkListDownloaded(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markListDownloaded, id)
	return err
}

const rotateListToken = `-- name: RotateListToken :exec
UPDATE filter_lists
SET token      = gen_random_uuid(),
    downloaded = false
WHERE user_id = $1
  AND token = $2
`

type RotateListTokenParams struct {
	UserID string
	Token  uuid.UUID
}

func (q *Queries) RotateListToken(ctx context.Context, arg RotateListTokenParams) error {
	_, err := q.db.Exec(ctx, rotateListToken, arg.UserID, arg.Token)
	return err
}
