name: "Dependabot PR helper"
on:
  push:
    branches:
      - 'dependabot/**'
jobs:
  regen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - name: Golang vendorsha
        run: |
          go mod tidy
          nix run .#update-vendorsha
      - name: Frontend assets
        run: |
          git rm -rf data/assets/dist/
          nix run .#update-assets
          git add data/assets/dist/
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "regenerate"
          git push
